# Generated by Django 6.0.3 on 2026-03-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık (Örn: Başarı Oranı)')),
                ('number', models.IntegerField(verbose_name='Sayı')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sembol (%, + vb.)')),
            ],
            options={
                'verbose_name': 'İstatistik',
                'verbose_name_plural': 'İstatistikler',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('role', models.CharField(max_length=100, verbose_name='Pozisyon')),
                ('description', models.TextField(verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Ekip Üyesi',
                'verbose_name_plural': 'Ekip Üyeleri',
            },
        ),
    ]
