# Generated by Django 6.0.3 on 2026-03-24 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı (Örn: SAP Hizmetleri)')),
                ('slug', models.SlugField(help_text="HTML'deki ID ile aynı olmalı", verbose_name='Kısa İsim (Örn: sap-solutions)')),
            ],
            options={
                'verbose_name': 'Hizmet Kategorisi',
                'verbose_name_plural': 'Hizmet Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Hizmet Başlığı')),
                ('description', models.TextField(verbose_name='Hizmet Açıklaması')),
                ('icon', models.CharField(max_length=100, verbose_name='İkon Sınıfı (Örn: flaticon-it-service)')),
                ('link', models.CharField(default='services-details.html', max_length=200, verbose_name='Detay Sayfası Linki')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='pages.servicecategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
            },
        ),
    ]
