# Generated by Django 6.0.3 on 2026-03-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_servicecategory_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İkon Sınıfı (Örn: flaticon-it-service)'),
        ),
    ]
