# Generated by Django 6.0.3 on 2026-03-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_service_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Haber Başlığı')),
                ('image', models.ImageField(upload_to='blog_images/', verbose_name='Haber Resmi')),
                ('author', models.CharField(default='Admin', max_length=100, verbose_name='Yazar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Duyuru/Haber',
                'verbose_name_plural': 'Duyurular/Haberler',
            },
        ),
    ]
