# Generated by Django 6.0.3 on 2026-03-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='slider_images/', verbose_name='Arka Plan Resmi')),
                ('btn1_text', models.CharField(default='Hizmetlerimiz', max_length=50, verbose_name='1. Buton Yazısı')),
                ('btn1_link', models.CharField(default='services-sap.html', max_length=200, verbose_name='1. Buton Linki')),
                ('btn2_text', models.CharField(default='İletişime Geç', max_length=50, verbose_name='2. Buton Yazısı')),
                ('btn2_link', models.CharField(default='contact.html', max_length=200, verbose_name='2. Buton Linki')),
            ],
            options={
                'verbose_name': 'Ana Ekran (Slider)',
                'verbose_name_plural': 'Ana Ekran (Slider)',
            },
        ),
    ]
