# Generated by Django 6.0.3 on 2026-03-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_years', models.IntegerField(default=4, verbose_name='Deneyim Yılı')),
                ('image', models.ImageField(upload_to='about_images/', verbose_name='Hakkımızda Resmi (Büyük)')),
                ('title', models.CharField(max_length=200, verbose_name='Ana Başlık')),
                ('description', models.TextField(verbose_name='Açıklama Yazısı')),
            ],
            options={
                'verbose_name': 'Hakkımızda Alanı',
                'verbose_name_plural': 'Hakkımızda Alanı',
            },
        ),
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Özellik Başlığı')),
                ('description', models.TextField(verbose_name='Özellik Açıklaması')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='İkon Sınıfı')),
            ],
            options={
                'verbose_name': 'Hakkımızda Özelliği',
                'verbose_name_plural': 'Hakkımızda Özellikleri',
            },
        ),
    ]
