# Generated by Django 6.0.3 on 2026-03-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_about_aboutfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Marka Adı')),
                ('image', models.ImageField(upload_to='brand_images/', verbose_name='Marka Logosu')),
            ],
            options={
                'verbose_name': 'Referans Marka',
                'verbose_name_plural': 'Referans Markalar',
            },
        ),
    ]
