# Generated by Django 6.0.3 on 2026-03-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='info@volltr.com', max_length=254, verbose_name='E-posta Adresi')),
                ('phone', models.CharField(default='+90 505 864 95 13', max_length=20, verbose_name='Telefon Numarası')),
                ('address', models.CharField(default='Ankara, Türkiye', max_length=255, verbose_name='Adres')),
                ('footer_text', models.TextField(default='Kurumsal çözümlerimiz ve dijital dönüşüm hizmetlerimizle işletmenize değer katıyoruz.', verbose_name='Footer Kısa Açıklama')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook Linki')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter (X) Linki')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram Linki')),
                ('pinterest', models.URLField(blank=True, null=True, verbose_name='Pinterest Linki')),
            ],
            options={
                'verbose_name': 'Site Ayarı',
                'verbose_name_plural': 'Genel Site Ayarları',
            },
        ),
    ]
