# Generated by Django 6.0.3 on 2026-03-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='Neden Biz?', max_length=100, verbose_name='Alt Başlık')),
                ('title', models.CharField(default='Özel BT Çözümleri ve Hizmetleri', max_length=200, verbose_name='Ana Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Neden Biz (Ana Bilgi)',
                'verbose_name_plural': 'Neden Biz (Ana Bilgi)',
            },
        ),
        migrations.CreateModel(
            name='ChooseUsFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Özellik Metni')),
            ],
            options={
                'verbose_name': 'Neden Biz Özelliği',
                'verbose_name_plural': 'Neden Biz Özellikleri',
            },
        ),
        migrations.CreateModel(
            name='CounterTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık (Örn: Tamamlanan Proje)')),
                ('number', models.IntegerField(verbose_name='Sayı')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sembol (+ vb.)')),
            ],
            options={
                'verbose_name': 'İkinci Sayaç',
                'verbose_name_plural': 'İkinci Sayaçlar',
            },
        ),
        migrations.CreateModel(
            name='MarqueeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Kayan Yazı Metni')),
            ],
            options={
                'verbose_name': 'Kayan Yazı',
                'verbose_name_plural': 'Kayan Yazılar',
            },
        ),
    ]
