# Generated by Django 6.0.3 on 2026-03-25 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_dark',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Koyu Logo (Normal)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_white',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Beyaz Logo (Şeffaf Menü İçin)'),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Menü Başlığı')),
                ('link', models.CharField(default='#', max_length=200, verbose_name='Sayfa Linki (Örn: about.html)')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama (Örn: 1, 2, 3)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.menuitem', verbose_name='Üst Menü (Eğer alt menüyse seçin)')),
            ],
            options={
                'verbose_name': 'Menü Elemanı',
                'verbose_name_plural': 'Menü Elemanları',
                'ordering': ['order'],
            },
        ),
    ]
