# Generated by Django 6.0.3 on 2026-03-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_sitesettings_logo_dark_sitesettings_logo_white_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(default='Tüm Hakları Saklıdır © 2025 VOLL', max_length=150, verbose_name='Telif Hakkı Yazısı'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='developer_text',
            field=models.CharField(default='Powered by Design furkandemirbas', max_length=150, verbose_name='Geliştirici Yazısı'),
        ),
    ]
