# Generated by Django 6.0.3 on 2026-03-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_sitesettings_copyright_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('description', models.CharField(max_length=255, verbose_name='Kısa Açıklama')),
                ('number', models.IntegerField(verbose_name='Sayı')),
                ('symbol', models.CharField(default='+', max_length=10, verbose_name='Sembol')),
            ],
            options={
                'verbose_name': 'Kurumsal Sayaç',
                'verbose_name_plural': 'Kurumsal Sayaçlar',
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_bg', models.ImageField(upload_to='about_images/', verbose_name='Üst Arka Plan Resmi')),
                ('image_1', models.ImageField(upload_to='about_images/', verbose_name='Sol Büyük Resim')),
                ('image_2', models.ImageField(upload_to='about_images/', verbose_name='Sağ Küçük Resim')),
                ('satisfaction_text', models.CharField(default='100% Müşteri Memnuniyeti', max_length=100, verbose_name='Memnuniyet Yazısı')),
                ('subtitle', models.CharField(default='Hakkımızda', max_length=100, verbose_name='Alt Başlık')),
                ('title', models.CharField(default='Dijital Dönüşüm Yolculuğunuzda Güvenilir İş Ortağınız', max_length=200, verbose_name='Ana Başlık')),
                ('description', models.TextField(verbose_name='Açıklama Yazısı')),
            ],
            options={
                'verbose_name': 'Kurumsal (Ana Bilgiler)',
                'verbose_name_plural': 'Kurumsal (Ana Bilgiler)',
            },
        ),
        migrations.CreateModel(
            name='AboutPageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Özellik Maddesi')),
            ],
            options={
                'verbose_name': 'Kurumsal Özellik Maddesi',
                'verbose_name_plural': 'Kurumsal Özellik Maddeleri',
            },
        ),
        migrations.CreateModel(
            name='ExpertiseArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_images/', verbose_name='Uzmanlık Resmi')),
                ('subtitle', models.CharField(default='Uzmanlıklarımız', max_length=100, verbose_name='Alt Başlık')),
                ('title', models.CharField(default='İşletmenizi Dijital Güçle Geleceğe Taşıyoruz', max_length=200, verbose_name='Ana Başlık')),
                ('description', models.TextField(verbose_name='Açıklama Yazısı')),
            ],
            options={
                'verbose_name': 'Uzmanlık Alanı (Ana Bilgiler)',
                'verbose_name_plural': 'Uzmanlık Alanı (Ana Bilgiler)',
            },
        ),
        migrations.CreateModel(
            name='ExpertiseSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Yetenek Adı (Örn: SAP Danışmanlığı)')),
                ('percentage', models.IntegerField(default=90, verbose_name='Yüzdelik Değer (Örn: 95)')),
            ],
            options={
                'verbose_name': 'Uzmanlık Yüzdesi',
                'verbose_name_plural': 'Uzmanlık Yüzdeleri',
            },
        ),
    ]
