# Generated by Django 6.0.3 on 2026-03-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_aboutcounter_aboutpage_aboutpagefeature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_bg', models.ImageField(upload_to='service_bg/', verbose_name='Sayfa Üst Arka Plan Resmi')),
            ],
            options={
                'verbose_name': 'Hizmetler Sayfası Ayarı',
                'verbose_name_plural': 'Hizmetler Sayfası Ayarları',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Hizmet Resmi (Detay sayfası için)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Kısa Açıklama'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İkon Sınıfı (Ana sayfa için)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='link',
            field=models.CharField(default='#', max_length=200, verbose_name='Yönlendirme Linki'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Hizmet Adı'),
        ),
    ]
