# Generated by Django 6.0.3 on 2026-03-26 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_servicepagesetting_service_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Kategori Başlığı (Örn: SAP Hizmetleri Referansları)')),
                ('subtitle', models.CharField(default='Güçlü İş Ortaklıkları', max_length=100, verbose_name='Alt Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Referans Kategorisi',
                'verbose_name_plural': 'Referans Kategorileri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReferencePageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_bg', models.ImageField(upload_to='reference_bg/', verbose_name='Sayfa Üst Arka Plan Resmi')),
            ],
            options={
                'verbose_name': 'Referanslar Sayfası Ayarı',
                'verbose_name_plural': 'Referanslar Sayfası Ayarları',
            },
        ),
        migrations.CreateModel(
            name='ReferenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Firma Adı')),
                ('image', models.ImageField(upload_to='references/', verbose_name='Firma Logosu')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='pages.referencecategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Referans Firma',
                'verbose_name_plural': 'Referans Firmalar',
            },
        ),
    ]
