# Generated by Django 6.0.3 on 2026-03-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_referencecategory_referencepagesetting_referenceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_bg', models.ImageField(upload_to='blog_bg/', verbose_name='Sayfa Üst Arka Plan Resmi')),
            ],
            options={
                'verbose_name': 'Blog Sayfası Ayarı',
                'verbose_name_plural': 'Blog Sayfası Ayarları',
            },
        ),
    ]
