# Generated by Django 6.0.3 on 2026-03-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_blogpagesetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Duyuru / Blog', 'verbose_name_plural': 'Duyurular / Bloglar'},
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Ana Metin (İçerik)'),
        ),
        migrations.AddField(
            model_name='blog',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama (Özet)'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(default='admin', max_length=100, verbose_name='Yazar'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blog_images/', verbose_name='Blog Resmi'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlık'),
        ),
    ]
