# Generated by Django 6.0.3 on 2026-03-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_blog_options_blog_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_bg', models.ImageField(upload_to='contact_bg/', verbose_name='Sayfa Üst Arka Plan Resmi')),
                ('address', models.CharField(default='INNOPARK Teknoloji Geliştirme Bölgesi SELÇUKLU / KONYA', max_length=255, verbose_name='Açık Adres')),
                ('map_iframe', models.TextField(default='https://maps.google.com/maps?q=INNOPARK+Teknoloji+Geliştirme+Bölgesi&t=&z=15&ie=UTF8&iwloc=&output=embed', verbose_name='Harita Iframe Linki (Sadece src içindeki linki girin)')),
            ],
            options={
                'verbose_name': 'İletişim Sayfası Ayarı',
                'verbose_name_plural': 'İletişim Sayfası Ayarları',
            },
        ),
    ]
