# Generated by Django 6.0.3 on 2026-03-26 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_contactpagesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcounter',
            name='about_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='pages.aboutpage', verbose_name='Bağlı Olduğu Sayfa'),
        ),
        migrations.AddField(
            model_name='aboutfeature',
            name='about',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pages.about', verbose_name='Bağlı Olduğu Hakkımızda Modülü'),
        ),
        migrations.AddField(
            model_name='aboutpagefeature',
            name='about_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pages.aboutpage', verbose_name='Bağlı Olduğu Sayfa'),
        ),
        migrations.AddField(
            model_name='chooseusfeature',
            name='choose_us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pages.chooseus', verbose_name='Bağlı Olduğu Neden Biz'),
        ),
        migrations.AddField(
            model_name='expertiseskill',
            name='expertise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='pages.expertisearea', verbose_name='Bağlı Olduğu Uzmanlık'),
        ),
    ]
