# Generated by Django 6.0.3 on 2026-03-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_aboutcounter_about_page_aboutfeature_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Açıklaması'),
        ),
        migrations.AddField(
            model_name='blog',
            name='seo_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='SEO Başlığı'),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Açıklaması'),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='SEO Başlığı'),
        ),
    ]
