# Generated by Django 6.0.3 on 2026-04-06 13:50

import pages.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_blog_seo_description_blog_seo_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='about_images/', validators=[pages.validators.validate_image_extension, pages.validators.validate_file_size], verbose_name='Hakkımızda Resmi (Büyük)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(upload_to='brand_images/', validators=[pages.validators.validate_image_extension, pages.validators.validate_file_size], verbose_name='Marka Logosu'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='slider_images/', validators=[pages.validators.validate_image_extension, pages.validators.validate_file_size], verbose_name='Arka Plan Resmi'),
        ),
    ]
