# Generated by Django 6.0.3 on 2026-05-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_alter_about_image_alter_brand_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referenceitem',
            options={'ordering': ['order'], 'verbose_name': 'Referans Firma', 'verbose_name_plural': 'Referans Firmalar'},
        ),
        migrations.AddField(
            model_name='referenceitem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AddField(
            model_name='referenceitem',
            name='show_on_homepage',
            field=models.BooleanField(default=False, verbose_name='Ana Sayfada Göster'),
        ),
    ]
