"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from pathlib import Path
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environ nesnesini başlat
env = environ.Env(
    DEBUG=(bool, False) # Cast DEBUG to boolean, default False
)

# .env dosyasını oku
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*']) # Canlı ortamda '*' yerine ['volltr.com', 'www.volltr.com'] gibi domainler yazılmalıdır.


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.forms',   # Wysiwyg editör için gerekli
    'unfold.contrib.filters', # Gelişmiş filtreler için
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps', # SEO İçin Site Haritası
    'adminsortable2',
    'pages',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # (Burada sizin templates yolunuz var)
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # AŞAĞIDAKİ SATIRI EKLEYİN:
                'pages.context_processors.global_settings', 
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'assets',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

from django.templatetags.static import static
from django.urls import reverse_lazy

UNFOLD = {
    "SITE_TITLE": "VOLL Yönetim",
    "SITE_HEADER": "VOLL Yönetim Paneli",
    "SITE_URL": "/",
    "DASHBOARD_CALLBACK": "pages.admin_dashboard.dashboard_callback",
    "SCRIPTS": [
        lambda request: static("js/admin_scroll.js"),
    ],
    "SITE_ICON": {
        "light": lambda request: static("img/logo/volllogodark.png"),
        "dark": lambda request: static("img/logo/volllogowhite.png"),
    },

    "SIDEBAR": {
        "show_search": True,  # Search in applications and models names
        "show_all_applications": False,  # Dropdown with all applications and models
        "navigation": [
            {
                "title": "Gezinme",
                "separator": True,
                "items": [
                    {"title": "Anasayfaya Dön", "icon": "home", "link": "/", "permission": lambda request: request.user.is_superuser},
                ],
            },
            {
                "title": "Anasayfa İçerikleri",
                "separator": True,
                "items": [
                    {"title": "Ana Ekran (Slider)", "icon": "image", "link": reverse_lazy("admin:pages_slider_changelist")},
                    {"title": "Markalar", "icon": "verified", "link": reverse_lazy("admin:pages_brand_changelist")},
                    {"title": "Kayan Yazılar", "icon": "linear_scale", "link": reverse_lazy("admin:pages_marqueeitem_changelist")},
                    {"title": "İstatistikler 2", "icon": "insert_chart", "link": reverse_lazy("admin:pages_countertwo_changelist")},
                    {"title": "Neden Biz (Ana Bilgi)", "icon": "lightbulb", "link": reverse_lazy("admin:pages_chooseus_changelist")},
                ],
            },
            {
                "title": "Kurumsal",
                "separator": True,
                "items": [
                    {"title": "Kurumsal Sayfası Ayarları", "icon": "business", "link": reverse_lazy("admin:pages_aboutpage_changelist")},
                    {"title": "Kurumsal Sayaçlar (120+, 85+ ...)", "icon": "analytics", "link": reverse_lazy("admin:pages_aboutcounter_changelist")},
                    {"title": "Uzmanlık Alanları", "icon": "star", "link": reverse_lazy("admin:pages_expertisearea_changelist")},
                    {"title": "Uzmanlık Yüzdeleri (Skill Barları)", "icon": "signal_cellular_alt", "link": reverse_lazy("admin:pages_expertiseskill_changelist")},
                    {"title": "Hakkımızda (Özet)", "icon": "info", "link": reverse_lazy("admin:pages_about_changelist")},
                    {"title": "Ekip Üyeleri", "icon": "groups", "link": reverse_lazy("admin:pages_teammember_changelist")},
                ],
            },
            {
                "title": "Hizmetler",
                "separator": True,
                "items": [
                    {"title": "Hizmetler Sayfa Ayarı", "icon": "settings_suggest", "link": reverse_lazy("admin:pages_servicepagesetting_changelist")},
                    {"title": "Hizmet Kategorileri (Hizmet Ekle)", "icon": "category", "link": reverse_lazy("admin:pages_servicecategory_changelist")},
                ],
            },
            {
                "title": "Referanslar",
                "separator": True,
                "items": [
                    {"title": "Referans Sayfa Ayarı", "icon": "settings_system_daydream", "link": reverse_lazy("admin:pages_referencepagesetting_changelist")},
                    {"title": "Referans Kategorileri (Referans Ekle)", "icon": "folder_special", "link": reverse_lazy("admin:pages_referencecategory_changelist")},
                ],
            },
            {
                "title": "Duyurular & Blog",
                "separator": True,
                "items": [
                    {"title": "Blog Sayfa Ayarı", "icon": "art_track", "link": reverse_lazy("admin:pages_blogpagesetting_changelist")},
                    {"title": "Bloglar / Duyurular", "icon": "campaign", "link": reverse_lazy("admin:pages_blog_changelist")},
                ],
            },
            {
                "title": "Ayarlar ve İletişim",
                "separator": True,
                "items": [
                    {"title": "Gelen Mesajlar", "icon": "mail", "link": reverse_lazy("admin:pages_contactmessage_changelist")},
                    {"title": "İletişim Sayfası Ayarı", "icon": "contact_support", "link": reverse_lazy("admin:pages_contactpagesetting_changelist")},
                    {"title": "Menü Elemanları (Navbar)", "icon": "menu", "link": reverse_lazy("admin:pages_menuitem_changelist")},
                    {"title": "Genel Site Ayarları", "icon": "settings", "link": reverse_lazy("admin:pages_sitesettings_changelist")},
                ],
            },
            {
                "title": "Güvenlik",
                "separator": True,
                "items": [
                    {"title": "Kullanıcılar", "icon": "person", "link": reverse_lazy("admin:auth_user_changelist")},
                    {"title": "Gruplar", "icon": "group", "link": reverse_lazy("admin:auth_group_changelist")},
                    {"title": "Yeni Kullanıcı Oluştur", "icon": "person_add", "link": "/kayit/", "permission": lambda request: request.user.is_superuser},
                ],
            },
        ],
    },
}

admin_url = env('ADMIN_URL', default='voll-gizli-yonetim/')

# ── Auth URL Ayarları ──
LOGIN_URL = '/giris/'
LOGIN_REDIRECT_URL = f'/{admin_url}'
LOGOUT_REDIRECT_URL = '/giris/'

# ── Güvenlik Ayarları ──
# XSS (Siteler Arası Komut Dosyası) Koruması
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# Clickjacking Koruması (Iframe ile sömürüyü engeller)
X_FRAME_OPTIONS = 'DENY'

# Çerez Güvenliği (XSS ile çerez çalınmasını zorlaştırır)
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True

# Production / Canlı ortam için HTTPS Zorunlulukları
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 yıl
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True